import React from 'react';
import ReactDOM from 'react-dom';
import FilmList from './Components/FilmList/FilmList';

let films = [
  {"Title":"Stranger Things","Year":"2016–","Rated":"TV-14","Released":"15 Jul 2016","Runtime":"55 min","Genre":"Drama, Fantasy, Horror","Director":"N/A","Writer":"Matt Duffer, Ross Duffer","Actors":"Winona Ryder, David Harbour, Finn Wolfhard, Millie Bobby Brown","Plot":"When a young boy disappears, his mother, a police chief, and his friends must confront terrifying forces in order to get him back.","Language":"English","Country":"USA","Awards":"Nominated for 2 Golden Globes. Another 2 wins & 17 nominations.","Poster":"https://images-na.ssl-images-amazon.com/images/M/MV5BMjEzMDAxOTUyMV5BMl5BanBnXkFtZTgwNzAxMzYzOTE@._V1_SX300.jpg","Metascore":"N/A","imdbRating":"9.0","imdbVotes":"239,544","imdbID":"tt4574334","Type":"series","totalSeasons":"2","Response":"True"},
  {"Title":"The OA","Year":"2016–","Rated":"N/A","Released":"16 Dec 2016","Runtime":"60 min","Genre":"Drama, Mystery","Director":"N/A","Writer":"Zal Batmanglij, Brit Marling","Actors":"Emory Cohen, Scott Wilson, Alice Krige, Patrick Gibson","Plot":"Having gone missing seven years ago, the previously blind Prairie returns home, now in her 20s with her sight restored. While many believe she is a miracle, others worry that she could be dangerous.","Language":"English","Country":"USA","Awards":"N/A","Poster":"https://images-na.ssl-images-amazon.com/images/M/MV5BMTc3MjA5NDM5N15BMl5BanBnXkFtZTgwOTgzNTQ4MDI@._V1_SX300.jpg","Metascore":"N/A","imdbRating":"8.1","imdbVotes":"18,679","imdbID":"tt4635282","Type":"series","totalSeasons":"1","Response":"True"},
  {"Title":"Designated Survivor","Year":"2016–","Rated":"TV-14","Released":"21 Sep 2016","Runtime":"60 min","Genre":"Drama, Thriller","Director":"N/A","Writer":"David Guggenheim","Actors":"Kiefer Sutherland, Natascha McElhone, Adan Canto, Italia Ricci","Plot":"A low-level Cabinet member becomes President of the United States after a catastrophic attack kills everyone above him in the Presidential line of succession.","Language":"English","Country":"USA","Awards":"1 win.","Poster":"https://images-na.ssl-images-amazon.com/images/M/MV5BMTY5NzYzODU4N15BMl5BanBnXkFtZTgwNzA1MjUwMDI@._V1_SX300.jpg","Metascore":"N/A","imdbRating":"8.0","imdbVotes":"19,228","imdbID":"tt5296406","Type":"series","totalSeasons":"1","Response":"True"}
];

ReactDOM.render(<FilmList list={ films } />, document.getElementById('application'));